on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '15'
      - run: make setup-ci
      - run: echo "wowowowow" && bananasplit
